name: Build & Deploy .NET Backend to Kubernetes

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Setup Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3️ Login to Docker Hub
      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # 4 Build & push Docker image
      - name: Build Docker image
        working-directory: WeatherApplication
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/dotnet-backend:latest -t ${{ secrets.DOCKERHUB_USERNAME }}/dotnet-backend:${{ github.sha }} .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/dotnet-backend:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/dotnet-backend:${{ github.sha }}

      # 5️ Deploy to Kubernetes via Bastion
      - name: Deploy backend to Kubernetes
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.EC2_BASTION_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/weatherapp/WeatherApplication
            git pull
            kubectl apply -f k8s/backend-deployment.yaml -n backend
            kubectl apply -f k8s/backend-service.yaml -n backend
